import { IWord } from "../types";

export const words: IWord[] = [
  // {
  //   id: 23,
  //   ru: "выступление",
  //   ta: "чыгыш",
  //   en: "performance",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/чыгыш.mp3",
  //   image: "https://fileserver.innoads.ru/uploads/chamala/performance.svg",
  // },
  {
    id: 27,
    ru: "парень",
    ta: "егет",
    en: "guy",
    audio: "https://fileserver.innoads.ru/uploads/chamala/егет.mp3",
    image: "https://fileserver.innoads.ru/uploads/chamala/guy.svg",
  },
  // {
  //   id: 18,
  //   ru: "мысль, идея",
  //   ta: "фикер",
  //   en: "thought, idea",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/фикер.mp3",
  //   image: "https://fileserver.innoads.ru/uploads/chamala/idea.svg",
  // },
  {
    id: 12,
    ru: "семья",
    ta: "гаилә",
    en: "family",
    audio: "https://fileserver.innoads.ru/uploads/chamala/гаилә.mp3",
    image: "https://fileserver.innoads.ru/uploads/chamala/family.svg",
  },
  {
    id: 16,
    ru: "служба, работа",
    ta: "хезмәт",
    en: "service, work",
    audio: "https://fileserver.innoads.ru/uploads/chamala/хезмәт.mp3",
    image: "https://fileserver.innoads.ru/uploads/chamala/work.svg",
  },
  // {
  //   id: 2,
  //   ru: "хозяйство",
  //   ta: "хуҗалык",
  //   en: "economy",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/хуҗалык.mp3",
  // },
  // {
  //   id: 26,
  //   ru: "управление",
  //   ta: "идарә",
  //   en: "management",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/идарә.mp3",
  // },
  {
    id: 31,
    ru: "дом",
    ta: "Өй",
    en: "house",
    audio: "https://fileserver.innoads.ru/uploads/chamala/өй.mp3",
  },
  {
    id: 340,
    ru: "город",
    ta: "шәһәр",
    en: "city",
    audio: "https://fileserver.innoads.ru/uploads/chamala/шәһәр.mp3",
  },
  {
    id: 29,
    ru: "вода",
    ta: "су",
    en: "water",
    audio: "https://fileserver.innoads.ru/uploads/chamala/су.mp3",
  },
  {
    id: 13,
    ru: "рубль",
    ta: "сум",
    en: "ruble",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сум.mp3",
  },
  {
    id: 9,
    ru: "ученик, читатель",
    ta: "укучы",
    en: "student, reader",
    audio: "https://fileserver.innoads.ru/uploads/chamala/укучы.mp3",
  },
  {
    id: 4,
    ru: "он/она/оно, сын",
    ta: "ул",
    en: "he/she/it, son",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ул.mp3",
  },
  {
    id: 14,
    ru: "место",
    ta: "урын",
    en: "place",
    audio: "https://fileserver.innoads.ru/uploads/chamala/урын.mp3",
  },
  {
    id: 30,
    ru: "время, пора",
    ta: "вакыт",
    en: "time",
    audio: "https://fileserver.innoads.ru/uploads/chamala/вакыт.mp3",
  },
  {
    id: 334,
    ru: "ладно",
    ta: "ярар",
    en: "okay",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ярар.mp3",
  },
  {
    id: 32,
    ru: "помощь, поддержка",
    ta: "ярдәм",
    en: "help, support",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ярдәм.mp3",
  },
  {
    id: 7,
    ru: "центр",
    ta: "Үзәк",
    en: "centre",
    audio: "https://fileserver.innoads.ru/uploads/chamala/үзәк.mp3",
  },
  // {
  //   id: 35,
  //   ru: "отдел, собрание",
  //   ta: "оешма",
  //   en: "department, meeting",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/оешма.mp3",
  // },
  {
    id: 58,
    ru: "луна, месяц",
    ta: "ай",
    en: "moon, month",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ай.mp3",
  },
  {
    id: 61,
    ru: "деньги",
    ta: "акча",
    en: "money",
    audio: "https://fileserver.innoads.ru/uploads/chamala/акча.mp3",
  },
  {
    id: 49,
    ru: "промежуток, расстояние",
    ta: "ара",
    en: "gap, distance",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ара.mp3",
  },
  {
    id: 69,
    ru: "голова",
    ta: "баш",
    en: "head",
    audio: "https://fileserver.innoads.ru/uploads/chamala/баш.mp3",
  },
  {
    id: 20,
    ru: "знание",
    ta: "белем",
    en: "knowledge",
    audio: "https://fileserver.innoads.ru/uploads/chamala/белем.mp3",
  },
  // {
  //   id: 71,
  //   ru: "религия, вера",
  //   ta: "дин",
  //   en: "religion, faith",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/дин.mp3",
  // },
  {
    id: 134,
    ru: "мама",
    ta: "әни",
    en: "mom",
    audio: "https://fileserver.innoads.ru/uploads/chamala/әни.mp3",
  },
  {
    id: 59,
    ru: "наука",
    ta: "фән",
    en: "science",
    audio: "https://fileserver.innoads.ru/uploads/chamala/фән.mp3",
  },
  // {
  //   id: 62,
  //   ru: "информация",
  //   ta: "мәгълүмат",
  //   en: "information",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мәгълүмат.mp3",
  // },
  // {
  //   id: 41,
  //   ru: "область",
  //   ta: "Өлкә",
  //   en: "area",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/өлкә.mp3",
  // },
  // {
  //   id: 64,
  //   ru: "вид, образ, облик",
  //   ta: "рәвеш",
  //   en: "type, image",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/рәвеш.mp3",
  // },
  {
    id: 53,
    ru: "состояние",
    ta: "хәл",
    en: "condition",
    audio: "https://fileserver.innoads.ru/uploads/chamala/хәл.mp3",
  },
  {
    id: 452,
    ru: "весна",
    ta: "яз",
    en: "spring",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яз.mp3",
  },
  {
    id: 22,
    ru: "творчество",
    ta: "иҗат",
    en: "creativity",
    audio: "https://fileserver.innoads.ru/uploads/chamala/иҗат.mp3",
  },
  {
    id: 136,
    ru: "девочка",
    ta: "кыз",
    en: "girl",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кыз.mp3",
  },
  // {
  //   id: 52,
  //   ru: "жизнь, бытие",
  //   ta: "тормыш",
  //   en: "life, being",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тормыш.mp3",
  // },
  // {
  //   id: 60,
  //   ru: "заместитель",
  //   ta: "урынбасар",
  //   en: "vice",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/урынбасар.mp3",
  // },
  // {
  //   id: 70,
  //   ru: "руководитель",
  //   ta: "Җитәкче",
  //   en: "Director",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/җитәкче.mp3",
  // },
  // {
  //   id: 371,
  //   ru: "гора",
  //   ta: "тау",
  //   en: "mountain",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тау.mp3",
  // },
  // {
  //   id: 36,
  //   ru: "период, этап, эпоха",
  //   ta: "чор",
  //   en: "period",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/чор.mp3",
  // },
  {
    id: 25,
    ru: "средство",
    ta: "чара",
    en: "instrument",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чара.mp3",
  },
  // {
  //   id: 33,
  //   ru: "степень, уровень, авторитет",
  //   ta: "дәрәҗә",
  //   en: "degree, level",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/дәрәҗә.mp3",
  // },
  // {
  //   id: 65,
  //   ru: "произведение",
  //   ta: "Әсәр",
  //   en: "composition",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/әсәр.mp3",
  // },
  {
    id: 68,
    ru: "запах",
    ta: "ис",
    en: "smell",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ис.mp3",
  },
  {
    id: 75,
    ru: "мир",
    ta: "дөнья",
    en: "world",
    audio: "https://fileserver.innoads.ru/uploads/chamala/дөнья.mp3",
  },
  {
    id: 6,
    ru: "имя, название",
    ta: "исем",
    en: "name",
    audio: "https://fileserver.innoads.ru/uploads/chamala/исем.mp3",
  },
  {
    id: 72,
    ru: "день",
    ta: "көн",
    en: "day",
    audio: "https://fileserver.innoads.ru/uploads/chamala/көн.mp3",
  },
  // {
  //   id: 89,
  //   ru: "цель",
  //   ta: "максат",
  //   en: "purpose",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/максат.mp3",
  // },
  // {
  //   id: 84,
  //   ru: "случай",
  //   ta: "очрак",
  //   en: "case",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/очрак.mp3",
  // },
  {
    id: 79,
    ru: "возможность",
    ta: "мөмкинлек",
    en: "possibility",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мөмкинлек.mp3",
  },
  // {
  //   id: 85,
  //   ru: "председатель",
  //   ta: "рәис",
  //   en: "chairman",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/рәис.mp3",
  // },
  {
    id: 77,
    ru: "число, количество",
    ta: "сан",
    en: "count",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сан.mp3",
  },
  {
    id: 92,
    ru: "война",
    ta: "сугыш",
    en: "war",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сугыш.mp3",
  },
  {
    id: 90,
    ru: "вопрос",
    ta: "сорау",
    en: "question",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сорау.mp3",
  },
  // {
  //   id: 86,
  //   ru: "рост, прирост",
  //   ta: "Үсеш",
  //   en: "growth",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/үсеш.mp3",
  // },
  {
    id: 78,
    ru: "возраст",
    ta: "яшь",
    en: "age",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яшь.mp3",
  },
  {
    id: 358,
    ru: "аптека",
    ta: "даруханә",
    en: "pharmacy",
    audio: "https://fileserver.innoads.ru/uploads/chamala/даруханә.mp3",
  },
  // {
  //   id: 376,
  //   ru: "озеро",
  //   ta: "күл",
  //   en: "lake",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/күл.mp3",
  // },
  {
    id: 140,
    ru: "ребёнок",
    ta: "бала",
    en: "child",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бала.mp3",
  },
  // {
  //   id: 11,
  //   ru: "результат, итог",
  //   ta: "нәтиҗә",
  //   en: "result, total",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/нәтиҗә.mp3",
  // },
  // {
  //   id: 42,
  //   ru: "действие",
  //   ta: "гамәл",
  //   en: "action",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/гамәл.mp3",
  // },
  // {
  //   id: 367,
  //   ru: "государство",
  //   ta: "дәүләт",
  //   en: "country",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/дәүләт.mp3",
  // },
  {
    id: 21,
    ru: "работа, труд",
    ta: "эш",
    en: "work",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эш.mp3",
  },
  {
    id: 352,
    ru: "можно",
    ta: "мөмкин",
    en: "may, possible",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мөмкин.mp3",
  },
  {
    id: 341,
    ru: "больница",
    ta: "хастаханә",
    en: "hospital",
    audio: "https://fileserver.innoads.ru/uploads/chamala/хастаханә.mp3",
  },
  {
    id: 137,
    ru: "младенец",
    ta: "бәби",
    en: "baby",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бәби.mp3",
  },
  {
    id: 132,
    ru: "младший брат",
    ta: "эне",
    en: "younger brother, junior",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эне.mp3",
  },
  {
    id: 139,
    ru: "бабушка",
    ta: "әби",
    en: "grandmother",
    audio: "https://fileserver.innoads.ru/uploads/chamala/әби.mp3",
  },
  {
    id: 128,
    ru: "родственники",
    ta: "туганнар",
    en: "relatives",
    audio: "https://fileserver.innoads.ru/uploads/chamala/туганнар.mp3",
  },
  {
    id: 38,
    ru: "человек",
    ta: "кеше",
    en: "human",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кеше.mp3",
  },
  // {
  //   id: 76,
  //   ru: "задача, проблема",
  //   ta: "мәсьәлә",
  //   en: "task, problem",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мәсьәлә.mp3",
  // },
  {
    id: 127,
    ru: "родственник",
    ta: "туган",
    en: "relative",
    audio: "https://fileserver.innoads.ru/uploads/chamala/туган.mp3",
  },
  // {
  //   id: 345,
  //   ru: "церковь",
  //   ta: "чиркәү",
  //   en: "church",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/чиркәү.mp3",
  // },
  // {
  //   id: 343,
  //   ru: "библиотека",
  //   ta: "китапханә",
  //   en: "library",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/китапханә.mp3",
  // },
  {
    id: 133,
    ru: "папа",
    ta: "әти",
    en: "dad",
    audio: "https://fileserver.innoads.ru/uploads/chamala/әти.mp3",
  },
  {
    id: 135,
    ru: "мальчик",
    ta: "малай",
    en: "boy",
    audio: "https://fileserver.innoads.ru/uploads/chamala/малай.mp3",
  },
  {
    id: 129,
    ru: "сестра, тётя",
    ta: "апа",
    en: "sister, aunt",
    audio: "https://fileserver.innoads.ru/uploads/chamala/апа.mp3",
  },
  {
    id: 131,
    ru: "брат, дядя",
    ta: "абый",
    en: "brother, uncle",
    audio: "https://fileserver.innoads.ru/uploads/chamala/абый.mp3",
  },
  {
    id: 518,
    ru: "живот",
    ta: "эч",
    en: "belly",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эч.mp3",
  },
  {
    id: 152,
    ru: "праздник",
    ta: "бәйрәм",
    en: "holiday",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бәйрәм.mp3",
  },
  {
    id: 368,
    ru: "народ",
    ta: "халык",
    en: "people",
    audio: "https://fileserver.innoads.ru/uploads/chamala/халык.mp3",
  },
  {
    id: 154,
    ru: "магазин",
    ta: "кибет",
    en: "shop",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кибет.mp3",
  },
  {
    id: 149,
    ru: "английский язык",
    ta: "инглиз теле",
    en: "English language",
    audio: "https://fileserver.innoads.ru/uploads/chamala/инглиз теле.mp3",
  },
  {
    id: 145,
    ru: "слово",
    ta: "сүз",
    en: "word",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сүз.mp3",
  },
  {
    id: 160,
    ru: "идти",
    ta: "барырга",
    en: "go",
    audio: "https://fileserver.innoads.ru/uploads/chamala/барырга.mp3",
  },
  {
    id: 165,
    ru: "понимать",
    ta: "аңларга",
    en: "understand",
    audio: "https://fileserver.innoads.ru/uploads/chamala/аңларга.mp3",
  },
  {
    id: 166,
    ru: "спрашивать, просить",
    ta: "сорарга",
    en: "ask",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сорарга.mp3",
  },
  {
    id: 159,
    ru: "знать",
    ta: "белергә",
    en: "know",
    audio: "https://fileserver.innoads.ru/uploads/chamala/белергә.mp3",
  },
  {
    id: 141,
    ru: "друг",
    ta: "дус",
    en: "friend",
    audio: "https://fileserver.innoads.ru/uploads/chamala/дус.mp3",
  },
  {
    id: 142,
    ru: "плохой, плохо",
    ta: "начар",
    en: "bad",
    audio: "https://fileserver.innoads.ru/uploads/chamala/начар.mp3",
  },
  {
    id: 162,
    ru: "возвращаться",
    ta: "кайтырга",
    en: "return",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кайтырга.mp3",
  },
  {
    id: 164,
    ru: "слушать",
    ta: "тыңларга",
    en: "listen",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тыңларга.mp3",
  },
  {
    id: 144,
    ru: "часы, час",
    ta: "сәгать",
    en: "hour, watch",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сәгать.mp3",
  },
  {
    id: 147,
    ru: "татарский язык",
    ta: "татар теле",
    en: "Tatar language",
    audio: "https://fileserver.innoads.ru/uploads/chamala/татар теле.mp3",
  },
  {
    id: 157,
    ru: "учиться, читать",
    ta: "укырга",
    en: "учиться, читать",
    audio: "https://fileserver.innoads.ru/uploads/chamala/укырга.mp3",
  },
  {
    id: 151,
    ru: "по-английски",
    ta: "инглизчә",
    en: "in English",
    audio: "https://fileserver.innoads.ru/uploads/chamala/инглизчә.mp3",
  },
  {
    id: 148,
    ru: "русский язык",
    ta: "рус теле",
    en: "Russian",
    audio: "https://fileserver.innoads.ru/uploads/chamala/рус теле.mp3",
  },
  {
    id: 150,
    ru: "по-русски",
    ta: "русча",
    en: "in Russian",
    audio: "https://fileserver.innoads.ru/uploads/chamala/русча.mp3",
  },
  {
    id: 459,
    ru: "черный",
    ta: "кара",
    en: "black",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кара.mp3",
  },
  {
    id: 355,
    ru: "деревня",
    ta: "авыл",
    en: "village",
    audio: "https://fileserver.innoads.ru/uploads/chamala/авыл.mp3",
  },
  {
    id: 24,
    ru: "женщина, жена",
    ta: "хатын",
    en: "woman, wife",
    audio: "https://fileserver.innoads.ru/uploads/chamala/хатын.mp3",
  },
  // {
  //   id: 51,
  //   ru: "культура",
  //   ta: "мәдәният",
  //   en: "culture",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мәдәният.mp3",
  // },
  {
    id: 354,
    ru: "песня",
    ta: "җыр",
    en: "song",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җыр.mp3",
  },
  {
    id: 365,
    ru: "великий",
    ta: "бөек",
    en: "great",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бөек.mp3",
  },
  {
    id: 351,
    ru: "можно?",
    ta: "мөмкинме?",
    en: "may I?",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мөмкинме.mp3",
  },
  {
    id: 366,
    ru: "страна",
    ta: "ил",
    en: "country",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ил.mp3",
  },
  // {
  //   id: 83,
  //   ru: "численность, счёт",
  //   ta: "исәп",
  //   en: "number, account",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/исәп.mp3",
  // },
  {
    id: 67,
    ru: "книга",
    ta: "китап",
    en: "book",
    audio: "https://fileserver.innoads.ru/uploads/chamala/китап.mp3",
  },
  // {
  //   id: 360,
  //   ru: "мечеть",
  //   ta: "мәчет",
  //   en: "mosque",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мәчет.mp3",
  // },
  {
    id: 353,
    ru: "урок",
    ta: "дәрес",
    en: "lesson",
    audio: "https://fileserver.innoads.ru/uploads/chamala/дәрес.mp3",
  },
  {
    id: 174,
    ru: "играть",
    ta: "уйнарга",
    en: "play",
    audio: "https://fileserver.innoads.ru/uploads/chamala/уйнарга.mp3",
  },
  {
    id: 167,
    ru: "сказать",
    ta: "әйтергә",
    en: "say",
    audio: "https://fileserver.innoads.ru/uploads/chamala/әйтергә.mp3",
  },
  {
    id: 168,
    ru: "брать",
    ta: "алырга",
    en: "take",
    audio: "https://fileserver.innoads.ru/uploads/chamala/алырга.mp3",
  },
  {
    id: 169,
    ru: "продавать",
    ta: "сатарга",
    en: "sell",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сатарга.mp3",
  },
  {
    id: 170,
    ru: "отвечать",
    ta: "җавап бирергә",
    en: "answer",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җавап бирергә.mp3",
  },
  {
    id: 172,
    ru: "встречаться",
    ta: "очрашырга",
    en: "meet up",
    audio: "https://fileserver.innoads.ru/uploads/chamala/очрашырга.mp3",
  },
  {
    id: 362,
    ru: "здание",
    ta: "бина",
    en: "building",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бина.mp3",
  },
  // {
  //   id: 364,
  //   ru: "древний",
  //   ta: "борынгы",
  //   en: "ancient",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/борынгы.mp3",
  // },
  {
    id: 382,
    ru: "грязный",
    ta: "пычрак",
    en: "dirty",
    audio: "https://fileserver.innoads.ru/uploads/chamala/пычрак.mp3",
  },
  {
    id: 383,
    ru: "чистый",
    ta: "чиста",
    en: "clean",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чиста.mp3",
  },
  {
    id: 384,
    ru: "высокий",
    ta: "биек",
    en: "high",
    audio: "https://fileserver.innoads.ru/uploads/chamala/биек.mp3",
  },
  {
    id: 385,
    ru: "низкий",
    ta: "тәбәнәк",
    en: "low",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тәбәнәк.mp3",
  },
  {
    id: 387,
    ru: "красивый",
    ta: "матур",
    en: "beautiful",
    audio: "https://fileserver.innoads.ru/uploads/chamala/матур.mp3",
  },
  {
    id: 388,
    ru: "некрасивый",
    ta: "ямьсез",
    en: "ugly",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ямьсез.mp3",
  },
  {
    id: 389,
    ru: "вкусный",
    ta: "тәмле",
    en: "tasty",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тәмле.mp3",
  },
  // {
  //   id: 369,
  //   ru: "музеи",
  //   ta: "музейлар",
  //   en: "museums",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/музейлар.mp3",
  // },
  // {
  //   id: 370,
  //   ru: "район",
  //   ta: "район",
  //   en: "district",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/район.mp3",
  // },
  // {
  //   id: 372,
  //   ru: "равнина",
  //   ta: "болын",
  //   en: "plain",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/болын.mp3",
  // },
  // {
  //   id: 373,
  //   ru: "природа",
  //   ta: "табигать",
  //   en: "nature",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/табигать.mp3",
  // },
  {
    id: 374,
    ru: "лес",
    ta: "урман",
    en: "forest",
    audio: "https://fileserver.innoads.ru/uploads/chamala/урман.mp3",
  },
  {
    id: 377,
    ru: "сад",
    ta: "бакча",
    en: "garden",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бакча.mp3",
  },
  // {
  //   id: 378,
  //   ru: "широкий",
  //   ta: "киң",
  //   en: "wide",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/киң.mp3",
  // },
  // {
  //   id: 379,
  //   ru: "узкий",
  //   ta: "тар",
  //   en: "narrow",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тар.mp3",
  // },
  {
    id: 381,
    ru: "маленький",
    ta: "кечкенә",
    en: "little",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кечкенә.mp3",
  },
  {
    id: 392,
    ru: "горячий",
    ta: "кайнар",
    en: "hot",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кайнар.mp3",
  },
  {
    id: 394,
    ru: "полезный",
    ta: "файдалы",
    en: "useful",
    audio: "https://fileserver.innoads.ru/uploads/chamala/файдалы.mp3",
  },
  {
    id: 395,
    ru: "бесполезный",
    ta: "файдасыз",
    en: "useless",
    audio: "https://fileserver.innoads.ru/uploads/chamala/файдасыз.mp3",
  },
  {
    id: 390,
    ru: "невкусный",
    ta: "тәмсез",
    en: "unpleasant",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тәмсез.mp3",
  },
  {
    id: 396,
    ru: "далёкий",
    ta: "ерак",
    en: "distant",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ерак.mp3",
  },
  {
    id: 375,
    ru: "река",
    ta: "елга",
    en: "river",
    audio: "https://fileserver.innoads.ru/uploads/chamala/елга.mp3",
  },
  // {
  //   id: 391,
  //   ru: "сладкий",
  //   ta: "баллы",
  //   en: "sweet",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/баллы.mp3",
  // },
  {
    id: 407,
    ru: "улица",
    ta: "урам",
    en: "street",
    audio: "https://fileserver.innoads.ru/uploads/chamala/урам.mp3",
  },
  {
    id: 408,
    ru: "дом",
    ta: "йорт, өй",
    en: "house",
    audio: "https://fileserver.innoads.ru/uploads/chamala/йорт, өй.mp3",
  },
  {
    id: 400,
    ru: "мягкий",
    ta: "йомшак",
    en: "soft",
    audio: "https://fileserver.innoads.ru/uploads/chamala/йомшак.mp3",
  },
  {
    id: 401,
    ru: "твёрдый",
    ta: "каты",
    en: "solids",
    audio: "https://fileserver.innoads.ru/uploads/chamala/каты.mp3",
  },
  {
    id: 402,
    ru: "утро",
    ta: "иртә",
    en: "morning",
    audio: "https://fileserver.innoads.ru/uploads/chamala/иртә.mp3",
  },
  {
    id: 404,
    ru: "вечер",
    ta: "кич",
    en: "evening",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кич.mp3",
  },
  {
    id: 405,
    ru: "ночь",
    ta: "төн",
    en: "night",
    audio: "https://fileserver.innoads.ru/uploads/chamala/төн.mp3",
  },
  {
    id: 406,
    ru: "гость",
    ta: "кунак",
    en: "guest",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кунак.mp3",
  },
  {
    id: 410,
    ru: "старый",
    ta: "иске",
    en: "old",
    audio: "https://fileserver.innoads.ru/uploads/chamala/иске.mp3",
  },
  {
    id: 411,
    ru: "новый",
    ta: "яңа",
    en: "new",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яңа.mp3",
  },
  {
    id: 412,
    ru: "этаж",
    ta: "кат",
    en: "floor",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кат.mp3",
  },
  {
    id: 413,
    ru: "комната",
    ta: "бүлмә",
    en: "room",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бүлмә.mp3",
  },
  // {
  //   id: 417,
  //   ru: "мебель",
  //   ta: "өй жиһазы",
  //   en: "furniture",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/өй жиһазы.mp3",
  // },
  // {
  //   id: 418,
  //   ru: "холодильник",
  //   ta: "суыткыч",
  //   en: "fridge",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/суыткыч.mp3",
  // },
  // {
  //   id: 419,
  //   ru: "стиральная машина",
  //   ta: "кер юу машинасы",
  //   en: "washing machine",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/кер юу машинасы.mp3",
  // },
  {
    id: 420,
    ru: "окно",
    ta: "тәрәзә",
    en: "window",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тәрәзә.mp3",
  },
  {
    id: 397,
    ru: "близкий",
    ta: "якын",
    en: "close, near",
    audio: "https://fileserver.innoads.ru/uploads/chamala/якын.mp3",
  },
  {
    id: 398,
    ru: "глубокий",
    ta: "тирән",
    en: "deep",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тирән.mp3",
  },
  // {
  //   id: 423,
  //   ru: "гостиная",
  //   ta: "кунак бүлмәсе",
  //   en: "living room",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/кунак бүлмәсе.mp3",
  // },
  // {
  //   id: 399,
  //   ru: "неглубокий, мелкий",
  //   ta: "сай",
  //   en: "shallow",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/сай.mp3",
  // },
  {
    id: 425,
    ru: "кухня",
    ta: "аш бүлмәсе",
    en: "kitchen",
    audio: "https://fileserver.innoads.ru/uploads/chamala/аш бүлмәсе.mp3",
  },
  {
    id: 422,
    ru: "лестница",
    ta: "баскыч",
    en: "ladder",
    audio: "https://fileserver.innoads.ru/uploads/chamala/баскыч.mp3",
  },
  // {
  //   id: 426,
  //   ru: "детская",
  //   ta: "балалар бүлмәсе",
  //   en: "children’s",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/балалар бүлмәсе.mp3",
  // },
  // {
  //   id: 427,
  //   ru: "ванная комната",
  //   ta: "юыну бүлмәсе",
  //   en: "bathroom",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/юыну бүлмәсе.mp3",
  // },
  {
    id: 428,
    ru: "стол",
    ta: "өстәл",
    en: "table",
    audio: "https://fileserver.innoads.ru/uploads/chamala/өстәл.mp3",
  },
  {
    id: 429,
    ru: "стул",
    ta: "урындык",
    en: "chair",
    audio: "https://fileserver.innoads.ru/uploads/chamala/урындык.mp3",
  },
  // {
  //   id: 430,
  //   ru: "шкаф",
  //   ta: "шкаф",
  //   en: "wardrobe",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/шкаф.mp3",
  // },
  // {
  //   id: 431,
  //   ru: "пылесос",
  //   ta: "тузан суыргыч",
  //   en: "a vacuum cleaner",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тузан суыргыч.mp3",
  // },
  {
    id: 432,
    ru: "подушка",
    ta: "мендәр",
    en: "pillow",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мендәр.mp3",
  },
  {
    id: 433,
    ru: "кровать",
    ta: "карават",
    en: "bed",
    audio: "https://fileserver.innoads.ru/uploads/chamala/карават.mp3",
  },
  {
    id: 434,
    ru: "одеяло",
    ta: "юрган",
    en: "blanket",
    audio: "https://fileserver.innoads.ru/uploads/chamala/юрган.mp3",
  },
  // {
  //   id: 435,
  //   ru: "коврик",
  //   ta: "палас",
  //   en: "carpet",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/палас.mp3",
  // },
  {
    id: 436,
    ru: "светлый",
    ta: "якты",
    en: "light",
    audio: "https://fileserver.innoads.ru/uploads/chamala/якты.mp3",
  },
  {
    id: 437,
    ru: "удобный",
    ta: "уңайлы",
    en: "comfortable",
    audio: "https://fileserver.innoads.ru/uploads/chamala/уңайлы.mp3",
  },
  {
    id: 439,
    ru: "там",
    ta: "анда",
    en: "there",
    audio: "https://fileserver.innoads.ru/uploads/chamala/анда.mp3",
  },
  {
    id: 440,
    ru: "здесь",
    ta: "монда",
    en: "here",
    audio: "https://fileserver.innoads.ru/uploads/chamala/монда.mp3",
  },
  {
    id: 441,
    ru: "тёплый",
    ta: "җылы",
    en: "warm",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җылы.mp3",
  },
  {
    id: 443,
    ru: "дождь",
    ta: "яңгыр",
    en: "rain",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яңгыр.mp3",
  },
  {
    id: 444,
    ru: "ветер",
    ta: "җил",
    en: "wind",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җил.mp3",
  },
  {
    id: 445,
    ru: "снег",
    ta: "кар",
    en: "snow",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кар.mp3",
  },
  {
    id: 446,
    ru: "любовь",
    ta: "мәхәббәт",
    en: "love",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мәхәббәт.mp3",
  },
  {
    id: 449,
    ru: "завтра",
    ta: "иртәгә",
    en: "tomorrow",
    audio: "https://fileserver.innoads.ru/uploads/chamala/иртәгә.mp3",
  },
  {
    id: 450,
    ru: "вчера",
    ta: "кичә",
    en: "yesterday",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кичә.mp3",
  },
  // {
  //   id: 451,
  //   ru: "погода",
  //   ta: "һава торышы",
  //   en: "weather",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/һава торышы.mp3",
  // },
  {
    id: 453,
    ru: "лето",
    ta: "җәй",
    en: "summer",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җәй.mp3",
  },
  {
    id: 462,
    ru: "зеленый",
    ta: "яшел",
    en: "green",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яшел.mp3",
  },
  // {
  //   id: 463,
  //   ru: "серый",
  //   ta: "соры",
  //   en: "grey",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/соры.mp3",
  // },
  // {
  //   id: 465,
  //   ru: "фиолетовый",
  //   ta: "шәмәхә",
  //   en: "violet",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/шәмәхә.mp3",
  // },
  {
    id: 466,
    ru: "один",
    ta: "бер",
    en: "one",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бер.mp3",
  },
  {
    id: 467,
    ru: "два",
    ta: "ике",
    en: "two",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ике.mp3",
  },
  {
    id: 468,
    ru: "три",
    ta: "өч",
    en: "three",
    audio: "https://fileserver.innoads.ru/uploads/chamala/өч.mp3",
  },
  {
    id: 469,
    ru: "четыре",
    ta: "дүрт",
    en: "four",
    audio: "https://fileserver.innoads.ru/uploads/chamala/дүрт.mp3",
  },
  {
    id: 470,
    ru: "пять",
    ta: "биш",
    en: "five",
    audio: "https://fileserver.innoads.ru/uploads/chamala/биш.mp3",
  },
  {
    id: 471,
    ru: "шесть",
    ta: "алты",
    en: "six",
    audio: "https://fileserver.innoads.ru/uploads/chamala/алты.mp3",
  },
  {
    id: 473,
    ru: "восемь",
    ta: "сигез",
    en: "eight",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сигез.mp3",
  },
  {
    id: 474,
    ru: "девять",
    ta: "тугыз",
    en: "nine",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тугыз.mp3",
  },
  {
    id: 475,
    ru: "десять",
    ta: "ун",
    en: "ten",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ун.mp3",
  },
  {
    id: 476,
    ru: "цветок",
    ta: "чәчәк",
    en: "flower",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чәчәк.mp3",
  },
  {
    id: 478,
    ru: "рыба",
    ta: "балык",
    en: "fish",
    audio: "https://fileserver.innoads.ru/uploads/chamala/балык.mp3",
  },
  {
    id: 479,
    ru: "мясо",
    ta: "ит",
    en: "meat",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ит.mp3",
  },
  {
    id: 480,
    ru: "курица",
    ta: "тавык",
    en: "chicken",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тавык.mp3",
  },
  {
    id: 481,
    ru: "птица",
    ta: "кош",
    en: "bird",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кош.mp3",
  },
  // {
  //   id: 483,
  //   ru: "растение",
  //   ta: "үсемлек",
  //   en: "plant",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/үсемлек.mp3",
  // },
  {
    id: 484,
    ru: "одежда",
    ta: "кием",
    en: "clothes",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кием.mp3",
  },
  {
    id: 485,
    ru: "брюки",
    ta: "чалбар",
    en: "pants",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чалбар.mp3",
    image: "https://fileserver.innoads.ru/uploads/chamala/pants.svg",
  },
  // {
  //   id: 487,
  //   ru: "шапка",
  //   ta: "башлык, баш киеме",
  //   en: "cap",
  //   audio:
  //     "https://fileserver.innoads.ru/uploads/chamala/башлык, баш киеме.mp3",
  // },
  {
    id: 458,
    ru: "белый",
    ta: "ак",
    en: "white",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ак.mp3",
  },
  {
    id: 457,
    ru: "желтый",
    ta: "сары",
    en: "yellow",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сары.mp3",
  },
  {
    id: 460,
    ru: "розовый",
    ta: "алсу",
    en: "pink",
    audio: "https://fileserver.innoads.ru/uploads/chamala/алсу.mp3",
  },
  {
    id: 495,
    ru: "рука",
    ta: "кул",
    en: "hand",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кул.mp3",
  },
  {
    id: 514,
    ru: "глаз",
    ta: "күз",
    en: "eye",
    audio: "https://fileserver.innoads.ru/uploads/chamala/күз.mp3",
  },
  // {
  //   id: 488,
  //   ru: "обувь",
  //   ta: "аяк киеме",
  //   en: "shoes",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/аяк киеме.mp3",
  // },
  // {
  //   id: 489,
  //   ru: "верхняя одежда",
  //   ta: "өс киеме",
  //   en: "outerwear",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/өс киеме.mp3",
  // },
  // {
  //   id: 490,
  //   ru: "детская одежда",
  //   ta: "балалар киеме",
  //   en: "children's clothing",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/балалар киеме.mp3",
  // },
  // {
  //   id: 491,
  //   ru: "косметика",
  //   ta: "бизәнү әйберләре",
  //   en: "cosmetic",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/бизәнү әйберләре.mp3",
  // },
  {
    id: 492,
    ru: "игрушка",
    ta: "уенчык",
    en: "toy",
    audio: "https://fileserver.innoads.ru/uploads/chamala/уенчык.mp3",
  },
  // {
  //   id: 493,
  //   ru: "юбка",
  //   ta: "итәк",
  //   en: "skirt",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/итәк.mp3",
  // },
  {
    id: 496,
    ru: "облако",
    ta: "болыт",
    en: "cloud",
    audio: "https://fileserver.innoads.ru/uploads/chamala/болыт.mp3",
  },
  {
    id: 497,
    ru: "сегодня",
    ta: "бүген",
    en: "today",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бүген.mp3",
  },
  {
    id: 500,
    ru: "погода",
    ta: "һава торышы",
    en: "weather",
    audio: "https://fileserver.innoads.ru/uploads/chamala/һава торышы.mp3",
  },
  {
    id: 503,
    ru: "осень",
    ta: "көз",
    en: "autumn",
    audio: "https://fileserver.innoads.ru/uploads/chamala/көз.mp3",
  },
  {
    id: 504,
    ru: "зима",
    ta: "кыш",
    en: "winter",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кыш.mp3",
  },
  {
    id: 505,
    ru: "красный",
    ta: "кызыл",
    en: "red",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кызыл.mp3",
  },
  {
    id: 507,
    ru: "тело",
    ta: "тән",
    en: "body",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тән.mp3",
  },
  {
    id: 509,
    ru: "палец",
    ta: "бармак",
    en: "finger",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бармак.mp3",
  },
  {
    id: 513,
    ru: "ухо",
    ta: "колак",
    en: "ear",
    audio: "https://fileserver.innoads.ru/uploads/chamala/колак.mp3",
  },
  {
    id: 515,
    ru: "нос",
    ta: "борын",
    en: "nose",
    audio: "https://fileserver.innoads.ru/uploads/chamala/борын.mp3",
  },
  {
    id: 517,
    ru: "рот",
    ta: "авыз",
    en: "mouth",
    audio: "https://fileserver.innoads.ru/uploads/chamala/авыз.mp3",
  },
  {
    id: 510,
    ru: "лицо, страница",
    ta: "бит",
    en: "face",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бит.mp3",
  },
  {
    id: 511,
    ru: "спина",
    ta: "арка",
    en: "back",
    audio: "https://fileserver.innoads.ru/uploads/chamala/арка.mp3",
  },
  {
    id: 512,
    ru: "волосы",
    ta: "чәч, чәчләр",
    en: "hair",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чәч, чәчләр.mp3",
  },
  {
    id: 519,
    ru: "язык",
    ta: "тел",
    en: "language, tongue",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тел.mp3",
  },
  {
    id: 521,
    ru: "напиток",
    ta: "эчемлек",
    en: "drink",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эчемлек.mp3",
  },
  {
    id: 522,
    ru: "хлеб",
    ta: "икмәк, ипи",
    en: "bread",
    audio: "https://fileserver.innoads.ru/uploads/chamala/икмәк, ипи.mp3",
  },
  {
    id: 523,
    ru: "масло",
    ta: "май",
    en: "butter",
    audio: "https://fileserver.innoads.ru/uploads/chamala/май.mp3",
  },
  {
    id: 524,
    ru: "молоко",
    ta: "сөт",
    en: "milk",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сөт.mp3",
  },
  {
    id: 525,
    ru: "яйцо",
    ta: "күкәй, йомырка",
    en: "egg",
    audio: "https://fileserver.innoads.ru/uploads/chamala/күкәй, йомырка.mp3",
  },
  {
    id: 527,
    ru: "чай",
    ta: "чәй",
    en: "tea",
    audio: "https://fileserver.innoads.ru/uploads/chamala/чәй.mp3",
  },
  {
    id: 528,
    ru: "мёд",
    ta: "бал",
    en: "honey",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бал.mp3",
  },
  {
    id: 529,
    ru: "фрукты",
    ta: "җилэк-җимеш",
    en: "fruit",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җилэк-җимеш.mp3",
  },
  {
    id: 530,
    ru: "овощ",
    ta: "яшелчә",
    en: "vegetable",
    audio: "https://fileserver.innoads.ru/uploads/chamala/яшелчә.mp3",
  },
  {
    id: 532,
    ru: "морковь",
    ta: "кишер",
    en: "carrot",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кишер.mp3",
  },
  {
    id: 533,
    ru: "огурец",
    ta: "кыяр",
    en: "cucumber",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кыяр.mp3",
  },
  {
    id: 534,
    ru: "капуста",
    ta: "кәбестә",
    en: "cabbage",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кәбестә.mp3",
  },
  {
    id: 535,
    ru: "яблоко",
    ta: "алма",
    en: "apple",
    audio: "https://fileserver.innoads.ru/uploads/chamala/алма.mp3",
  },
  {
    id: 538,
    ru: "суп",
    ta: "аш",
    en: "soup",
    audio: "https://fileserver.innoads.ru/uploads/chamala/аш.mp3",
  },
  {
    id: 539,
    ru: "каша",
    ta: "ботка",
    en: "cereal",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ботка.mp3",
  },
  {
    id: 540,
    ru: "соль",
    ta: "тоз",
    en: "salt",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тоз.mp3",
  },
  // {
  //   id: 541,
  //   ru: "скидка",
  //   ta: "ташлама",
  //   en: "discount",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/ташлама.mp3",
  // },
  {
    id: 543,
    ru: "дорогой (о цене)",
    ta: "кыйбат",
    en: "expensive",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кыйбат.mp3",
  },
  {
    id: 544,
    ru: "цена",
    ta: "бәя",
    en: "price",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бәя.mp3",
  },
  // {
  //   id: 545,
  //   ru: "медведь",
  //   ta: "аю",
  //   en: "bear",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/аю.mp3",
  // },
  {
    id: 546,
    ru: "лиса",
    ta: "төлке",
    en: "fox",
    audio: "https://fileserver.innoads.ru/uploads/chamala/төлке.mp3",
  },
  {
    id: 548,
    ru: "заяц",
    ta: "куян",
    en: "hare",
    audio: "https://fileserver.innoads.ru/uploads/chamala/куян.mp3",
  },
  {
    id: 57,
    ru: "привет",
    ta: "сәлам",
    en: "hi",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сәлам.mp3",
  },
  // {
  //   id: 19,
  //   ru: "сотрудник",
  //   ta: "хезмәткәр",
  //   en: "employee",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/хезмәткәр.mp3",
  // },
  {
    id: 40,
    ru: "дорога, путь",
    ta: "юл",
    en: "path, way",
    audio: "https://fileserver.innoads.ru/uploads/chamala/юл.mp3",
  },
  // {
  //   id: 74,
  //   ru: "сила, могущество",
  //   ta: "көч",
  //   en: "strength, power",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/көч.mp3",
  // },
  // {
  //   id: 93,
  //   ru: "просвещение, образование",
  //   ta: "мәгариф",
  //   en: "education",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мәгариф.mp3",
  // },
  {
    id: 155,
    ru: "школа",
    ta: "мәктәп",
    en: "school",
    audio: "https://fileserver.innoads.ru/uploads/chamala/мәктәп.mp3",
  },
  // {
  //   id: 55,
  //   ru: "мусульманин",
  //   ta: "мөселман",
  //   en: "muslim",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/мөселман.mp3",
  // },
  // {
  //   id: 87,
  //   ru: "встреча",
  //   ta: "очрашу",
  //   en: "meeting",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/очрашу.mp3",
  // },
  // {
  //   id: 50,
  //   ru: "часть, доля, порция",
  //   ta: "Өлеш",
  //   en: "part",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/өлеш.mp3",
  // },
  // {
  //   id: 95,
  //   ru: "стихотворение",
  //   ta: "шигырь",
  //   en: "poem",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/шигырь.mp3",
  // },
  // {
  //   id: 94,
  //   ru: "сторона",
  //   ta: "тараф",
  //   en: "side",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тараф.mp3",
  // },
  {
    id: 63,
    ru: "история",
    ta: "тарих",
    en: "history",
    audio: "https://fileserver.innoads.ru/uploads/chamala/тарих.mp3",
  },
  {
    id: 175,
    ru: "учитель",
    ta: "укытучы",
    en: "teacher",
    audio: "https://fileserver.innoads.ru/uploads/chamala/укытучы.mp3",
  },
  {
    id: 363,
    ru: "столица",
    ta: "башкала",
    en: "capital",
    audio: "https://fileserver.innoads.ru/uploads/chamala/башкала.mp3",
  },
  {
    id: 551,
    ru: "корова",
    ta: "сыер",
    en: "cow",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сыер.mp3",
  },
  {
    id: 552,
    ru: "лошадь",
    ta: "ат",
    en: "horse",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ат.mp3",
  },
  {
    id: 554,
    ru: "дружба",
    ta: "дуслык",
    en: "friendship",
    audio: "https://fileserver.innoads.ru/uploads/chamala/дуслык.mp3",
  },
  // {
  //   id: 556,
  //   ru: "надежда",
  //   ta: "өмет",
  //   en: "hope",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/өмет.mp3",
  // },
  // {
  //   id: 34,
  //   ru: "представитель",
  //   ta: "вәкил",
  //   en: "representative",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/вәкил.mp3",
  // },
  // {
  //   id: 43,
  //   ru: "земля",
  //   ta: "Җир",
  //   en: "Earth",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/җир.mp3",
  // },
  {
    id: 173,
    ru: "заплатить",
    ta: "түләргә",
    en: "pay",
    audio: "https://fileserver.innoads.ru/uploads/chamala/түләргә.mp3",
  },
  {
    id: 158,
    ru: "работать",
    ta: "эшләргә",
    en: "work",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эшләргә.mp3",
  },
  // {
  //   id: 386,
  //   ru: "рядом с",
  //   ta: "янында",
  //   en: "near",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/янында.mp3",
  // },
  {
    id: 163,
    ru: "разговаривать",
    ta: "сөйләшергә",
    en: "talk",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сөйләшергә.mp3",
  },
  {
    id: 380,
    ru: "большой",
    ta: "зур",
    en: "big",
    audio: "https://fileserver.innoads.ru/uploads/chamala/зур.mp3",
  },
  {
    id: 393,
    ru: "холодный",
    ta: "салкын",
    en: "cold",
    audio: "https://fileserver.innoads.ru/uploads/chamala/салкын.mp3",
  },
  {
    id: 409,
    ru: "квартира",
    ta: "фатир",
    en: "apartment",
    audio: "https://fileserver.innoads.ru/uploads/chamala/фатир.mp3",
  },
  // {
  //   id: 416,
  //   ru: "остановка",
  //   ta: "тукталыш",
  //   en: "station",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/тукталыш.mp3",
  // },
  {
    id: 421,
    ru: "дверь",
    ta: "ишек",
    en: "door",
    audio: "https://fileserver.innoads.ru/uploads/chamala/ишек.mp3",
  },
  // {
  //   id: 424,
  //   ru: "спальня",
  //   ta: "йокы бүлмәсе",
  //   en: "bedroom",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/йокы бүлмәсе.mp3",
  // },
  {
    id: 442,
    ru: "холодный",
    ta: "салкын",
    en: "cold",
    audio: "https://fileserver.innoads.ru/uploads/chamala/салкын.mp3",
  },
  {
    id: 448,
    ru: "сегодня",
    ta: "бүген",
    en: "today",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бүген.mp3",
  },
  {
    id: 461,
    ru: "синий",
    ta: "зәңгәр",
    en: "blue",
    audio: "https://fileserver.innoads.ru/uploads/chamala/зәңгәр.mp3",
  },
  {
    id: 464,
    ru: "коричневый",
    ta: "көрән",
    en: "brown",
    audio: "https://fileserver.innoads.ru/uploads/chamala/көрән.mp3",
  },
  {
    id: 472,
    ru: "семь",
    ta: "җиде",
    en: "seven",
    audio: "https://fileserver.innoads.ru/uploads/chamala/җиде.mp3",
  },
  {
    id: 477,
    ru: "дерево",
    ta: "агач",
    en: "tree",
    audio: "https://fileserver.innoads.ru/uploads/chamala/агач.mp3",
  },
  {
    id: 482,
    ru: "животное",
    ta: "хайван",
    en: "animal",
    audio: "https://fileserver.innoads.ru/uploads/chamala/хайван.mp3",
  },
  {
    id: 486,
    ru: "рубашка, платье",
    ta: "күлмәк",
    en: "shirt",
    audio: "https://fileserver.innoads.ru/uploads/chamala/күлмәк.mp3",
  },
  {
    id: 516,
    ru: "зуб",
    ta: "теш",
    en: "tooth",
    audio: "https://fileserver.innoads.ru/uploads/chamala/теш.mp3",
  },
  // {
  //   id: 520,
  //   ru: "еда",
  //   ta: "ашамлык",
  //   en: "food",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/ашамлык.mp3",
  // },
  // {
  //   id: 526,
  //   ru: "пирог",
  //   ta: "бәлеш",
  //   en: "pie",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/бәлеш.mp3",
  // },
  {
    id: 531,
    ru: "картофель",
    ta: "бәрәңге",
    en: "potato",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бәрәңге.mp3",
  },
  {
    id: 536,
    ru: "сахар",
    ta: "шикәр",
    en: "sugar",
    audio: "https://fileserver.innoads.ru/uploads/chamala/шикәр.mp3",
  },
  {
    id: 542,
    ru: "дешёвый",
    ta: "арзан",
    en: "cheap",
    audio: "https://fileserver.innoads.ru/uploads/chamala/арзан.mp3",
  },
  {
    id: 547,
    ru: "волк",
    ta: "бүре",
    en: "wolf",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бүре.mp3",
  },
  {
    id: 549,
    ru: "собака",
    ta: "эт",
    en: "dog",
    audio: "https://fileserver.innoads.ru/uploads/chamala/эт.mp3",
  },
  {
    id: 550,
    ru: "кошка",
    ta: "песи",
    en: "cat",
    audio: "https://fileserver.innoads.ru/uploads/chamala/песи.mp3",
  },
  // {
  //   id: 555,
  //   ru: "уважение",
  //   ta: "хөрмәт",
  //   en: "respect",
  //   audio: "https://fileserver.innoads.ru/uploads/chamala/хөрмәт.mp3",
  // },
  {
    id: 146,
    ru: "по-татарски",
    ta: "татарча",
    en: "in Tatar",
    audio: "https://fileserver.innoads.ru/uploads/chamala/татарча.mp3",
  },
  {
    id: 138,
    ru: "дедушка",
    ta: "бабай",
    en: "grandfather",
    audio: "https://fileserver.innoads.ru/uploads/chamala/бабай.mp3",
  },
  {
    id: 81,
    ru: "девочка/девушка, дочь",
    ta: "кыз",
    en: "girl, daughter",
    audio: "https://fileserver.innoads.ru/uploads/chamala/кыз.mp3",
  },
  {
    id: 130,
    ru: "младшая сестра",
    ta: "сеңел",
    en: "younger sister",
    audio: "https://fileserver.innoads.ru/uploads/chamala/сеңел.mp3",
  },
  {
    id: 156,
    ru: "детский сад",
    ta: "балалар бакчасы",
    en: "kindergarten",
    audio: "https://fileserver.innoads.ru/uploads/chamala/балалар бакчасы.mp3",
  },
];
